name: Test .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet tool install --global Codecov.Tool
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
        find ./MyLibraryTest/TestResults -type f -name coverage.cobertura.xml -exec cp . \;
        ls 
        #codecov -v -f "MyLibraryTest/TestResults/coverage/**/*.xml" -t ${{ secrets.CODECOV_TOKEN }}
        codecov -v -f coverage.cobertura.xml -t ${{ secrets.CODECOV_TOKEN }}
